CREATE TABLE DATABASE.CONFIGURATION (
    "CONF_ID" INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(100),
    "CREATOR" VARCHAR(100),
    "CREATION_TIME" DATE,
    "LAST_UPDATE" DATE
);

CREATE TABLE DATABASE.COMPONENT (
    "COMP_ID" INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
    "VENDOR" VARCHAR(100),
    "PRICE" DECIMAL,
    "TYPE" VARCHAR(20),
    "POWER" INTEGER,
    "NAME" VARCHAR(100)
);

CREATE TABLE DATABASE.PCSET (
    "COMP_ID" INTEGER NOT NULL,
    "CONF_ID" INTEGER NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    CONSTRAINT "COMP" FOREIGN KEY ("COMP_ID") REFERENCES DATABASE.COMPONENT("COMP_ID"),
    CONSTRAINT "CONF" FOREIGN KEY ("CONF_ID") REFERENCES DATABASE.CONFIGURATION("CONF_ID"),
    CONSTRAINT "PC_SET" PRIMARY KEY ("COMP_ID", "CONF_ID")
);