CREATE TABLE DATABASE.CONFIGURATION (
    "CONF_ID" INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(100) NOT NULL,
    "CREATOR" VARCHAR(100) NOT NULL,
    "CREATION_TIME" DATE NOT NULL,
    "LAST_UPDATE" DATE NOT NULL
);

CREATE TABLE DATABASE.COMPONENT (
    "COMP_ID" INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
    "VENDOR" VARCHAR(100) NOT NULL,
    "PRICE" DECIMAL NOT NULL,
    "TYPE" VARCHAR(20) NOT NULL,
    "POWER" INTEGER NOT NULL,
    "NAME" VARCHAR(100) NOT NULL
);

CREATE TABLE DATABASE.PCSET (
    "COMP_ID" INTEGER NOT NULL,
    "CONF_ID" INTEGER NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    CONSTRAINT "COMP" FOREIGN KEY ("COMP_ID") REFERENCES DATABASE.COMPONENT("COMP_ID"),
    CONSTRAINT "CONF" FOREIGN KEY ("CONF_ID") REFERENCES DATABASE.CONFIGURATION("CONF_ID"),
    CONSTRAINT "PC_SET" PRIMARY KEY ("COMP_ID", "CONF_ID")
);