/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pcconfigurator.gui.frames;

import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.SwingWorker;
import pcconfigurator.componentmanager.Component;
import pcconfigurator.componentmanager.ComponentManager;
import pcconfigurator.componentmanager.ComponentManagerImpl;
import pcconfigurator.componentmanager.ComponentTypes;
import pcconfigurator.configurationmanager.Configuration;
import pcconfigurator.configurationmanager.ConfigurationManager;
import pcconfigurator.configurationmanager.ConfigurationManagerImpl;
import pcconfigurator.exception.InternalFailureException;
import pcconfigurator.gui.dialogs.AboutAppDialog;
import pcconfigurator.gui.dialogs.AddCompToConfDialog;
import pcconfigurator.gui.dialogs.CreateConfigurationDialog;
import pcconfigurator.gui.dialogs.DeleteConfigurationDialog;
import pcconfigurator.gui.dialogs.DeletePcSetDialog;
import pcconfigurator.gui.dialogs.EditAmountDialog;
import pcconfigurator.gui.dialogs.EditConfigurationDialog;
import pcconfigurator.gui.dialogs.WarningDialog;
import pcconfigurator.gui.tablemodels.ComponentsInConfigTableModel;
import pcconfigurator.gui.tablemodels.ConfigurationTableModel;
import pcconfigurator.pcsetmanager.PcSet;
import pcconfigurator.pcsetmanager.PcSetManager;
import pcconfigurator.pcsetmanager.PcSetManagerImpl;

/**
 *
 * @author Martin
 */
public class MainWindow extends javax.swing.JFrame {

    private final java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pcconfigurator/gui/Strings");
    private static final Logger LOGGER = Logger.getLogger(MainWindow.class.getName());

    private final ComponentManager compManager;
    private final ConfigurationManager configManager;
    private final PcSetManager pcSetManager;

    private final ConfigurationTableModel configModel;
    private final ComponentsInConfigTableModel compModel;

    private Component currentComponent;
    private Configuration configuration;
    private Configuration currentConfiguration;

    private final MainWindow mainWindow = this;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        pcSetManager = new PcSetManagerImpl();
        configManager = new ConfigurationManagerImpl();
        compManager = new ComponentManagerImpl();

        initComponents();
        configModel = (ConfigurationTableModel) configsTable.getModel();
        compModel = (ComponentsInConfigTableModel) compsInCofigTable.getModel();
        findAllConfigurations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        searchNameLabel = new javax.swing.JTextField();
        componentsComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        findConfigsByNameButton = new javax.swing.JButton();
        findConfigsByCompButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        configsTable = new javax.swing.JTable();
        editConfButton = new javax.swing.JButton();
        createConfButton = new javax.swing.JButton();
        deleteConfButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        confNameTextBox = new javax.swing.JLabel();
        confCreatorTextBox = new javax.swing.JLabel();
        createdOnTextBox = new javax.swing.JLabel();
        lastChangedOnTextBox = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        compsInCofigTable = new javax.swing.JTable();
        addCompToConfButton = new javax.swing.JButton();
        deleteCompInConfButton = new javax.swing.JButton();
        editAmountButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        totalPowerLabel = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        showAllConfsButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pcconfigurator/gui/Strings"); // NOI18N
        setTitle(bundle.getString("pcconfigurator")); // NOI18N
        setLocationByPlatform(true);
        setResizable(false);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText(bundle.getString("listOfConfigurations")); // NOI18N

        jLabel2.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        jLabel2.setText(bundle.getString("searchBy")); // NOI18N

        jLabel3.setText(bundle.getString("searchByName")); // NOI18N

        componentsComboBox.setModel(new javax.swing.DefaultComboBoxModel(getComponentStrings()));

        jLabel4.setText(bundle.getString("searchByComponent")); // NOI18N

        findConfigsByNameButton.setText(bundle.getString("search")); // NOI18N
        findConfigsByNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findConfigsByNameButtonActionPerformed(evt);
            }
        });

        findConfigsByCompButton.setText(bundle.getString("search")); // NOI18N
        findConfigsByCompButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findConfigsByCompButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel5.setText(bundle.getString("configuration")); // NOI18N

        configsTable.setModel(new ConfigurationTableModel());
        configsTable.setAutoscrolls(false);
        configsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        configsTable.getTableHeader().setReorderingAllowed(false);
        configsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(configsTable);
        if (configsTable.getColumnModel().getColumnCount() > 0) {
            configsTable.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("name")); // NOI18N
            configsTable.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("creator")); // NOI18N
            configsTable.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("created")); // NOI18N
            configsTable.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("lastChange")); // NOI18N
        }

        editConfButton.setText(bundle.getString("edit")); // NOI18N
        editConfButton.setEnabled(false);
        editConfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editConfButtonActionPerformed(evt);
            }
        });

        createConfButton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        createConfButton.setText(bundle.getString("createConfiguration")); // NOI18N
        createConfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createConfButtonActionPerformed(evt);
            }
        });

        deleteConfButton.setText(bundle.getString("delete")); // NOI18N
        deleteConfButton.setEnabled(false);
        deleteConfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteConfButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setText(bundle.getString("name")); // NOI18N

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setText(bundle.getString("creator")); // NOI18N

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setText(bundle.getString("created")); // NOI18N

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel9.setText(bundle.getString("lastChange")); // NOI18N

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        jLabel14.setText(bundle.getString("listOfComponents")); // NOI18N

        compsInCofigTable.setModel(new ComponentsInConfigTableModel());
        compsInCofigTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        compsInCofigTable.getTableHeader().setReorderingAllowed(false);
        compsInCofigTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                compsInCofigTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(compsInCofigTable);
        if (compsInCofigTable.getColumnModel().getColumnCount() > 0) {
            compsInCofigTable.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("vendor")); // NOI18N
            compsInCofigTable.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("name")); // NOI18N
            compsInCofigTable.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("type")); // NOI18N
            compsInCofigTable.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("price")); // NOI18N
            compsInCofigTable.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("power")); // NOI18N
            compsInCofigTable.getColumnModel().getColumn(5).setHeaderValue(bundle.getString("amount")); // NOI18N
        }

        addCompToConfButton.setText(bundle.getString("addComponent")); // NOI18N
        addCompToConfButton.setEnabled(false);
        addCompToConfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCompToConfButtonActionPerformed(evt);
            }
        });

        deleteCompInConfButton.setText(bundle.getString("deleteComponent")); // NOI18N
        deleteCompInConfButton.setEnabled(false);
        deleteCompInConfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCompInConfButtonActionPerformed(evt);
            }
        });

        editAmountButton.setText(bundle.getString("editAmount")); // NOI18N
        editAmountButton.setEnabled(false);
        editAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAmountButtonActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("sansserif", 2, 13)); // NOI18N
        jLabel15.setText(bundle.getString("totalPrice")); // NOI18N

        totalPriceLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("sansserif", 2, 13)); // NOI18N
        jLabel17.setText(bundle.getString("totalPower")); // NOI18N

        totalPowerLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel26.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel26.setText("€");

        jLabel27.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel27.setText("W");

        showAllConfsButton.setText(bundle.getString("showAll")); // NOI18N
        showAllConfsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllConfsButtonActionPerformed(evt);
            }
        });

        jMenu1.setText(bundle.getString("program")); // NOI18N

        jMenuItem1.setText(bundle.getString("about")); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText(bundle.getString("exit")); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText(bundle.getString("componentManager")); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createConfButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(showAllConfsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(searchNameLabel)
                                            .addComponent(componentsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(findConfigsByCompButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(findConfigsByNameButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editConfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteConfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel14)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(totalPriceLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(totalPowerLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel27)
                                        .addGap(15, 15, 15))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(addCompToConfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deleteCompInConfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editAmountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(confNameTextBox)
                                            .addComponent(confCreatorTextBox)
                                            .addComponent(createdOnTextBox)
                                            .addComponent(lastChangedOnTextBox)))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 1, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(showAllConfsButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(searchNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(findConfigsByNameButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(componentsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(findConfigsByCompButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editConfButton)
                            .addComponent(deleteConfButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createConfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(confNameTextBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(confCreatorTextBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(createdOnTextBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lastChangedOnTextBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(totalPriceLabel)
                            .addComponent(jLabel17)
                            .addComponent(totalPowerLabel)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCompToConfButton)
                            .addComponent(deleteCompInConfButton)
                            .addComponent(editAmountButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        ComponentManagerFrame compFrame = new ComponentManagerFrame();
        compFrame.setParentWindow(this);
        compFrame.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JDialog aboutApp = new AboutAppDialog(this, true);
        aboutApp.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void createConfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createConfButtonActionPerformed
        editConfButton.setEnabled(false);
        deleteConfButton.setEnabled(false);
        JDialog createConfiguration = new CreateConfigurationDialog(this, true);
        createConfiguration.setVisible(true);
    }//GEN-LAST:event_createConfButtonActionPerformed

    private void editConfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editConfButtonActionPerformed
        configuration = configModel.getConfiguration(configsTable.getSelectedRow());
        EditConfigurationDialog editConfiguration = new EditConfigurationDialog(this, true);
        editConfiguration.setTextFields(configuration.getName(), configuration.getCreator());
        editConfiguration.setVisible(true);
    }//GEN-LAST:event_editConfButtonActionPerformed

    private void editAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAmountButtonActionPerformed
        EditAmountDialog editAmount = new EditAmountDialog(this, true);
        editAmount.setCompAndConf(compModel.getComponentAt(compsInCofigTable.getSelectedRow()), currentConfiguration, Integer.parseInt((String) compsInCofigTable.getValueAt(compsInCofigTable.getSelectedRow(), 5)));
        editAmount.setVisible(true);
        editConfButton.setEnabled(false);
        deleteConfButton.setEnabled(false);
    }//GEN-LAST:event_editAmountButtonActionPerformed

    private void addCompToConfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCompToConfButtonActionPerformed
        AddCompToConfDialog addCompToConf = new AddCompToConfDialog(this, true);
        addCompToConf.setVisible(true);
        editConfButton.setEnabled(false);
        deleteConfButton.setEnabled(false);
    }//GEN-LAST:event_addCompToConfButtonActionPerformed

    private void deleteConfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteConfButtonActionPerformed
        DeleteConfigurationDialog deleteConfiguration = new DeleteConfigurationDialog(this, true);
        deleteConfiguration.setConfToDelete(configModel.getConfiguration(configsTable.getSelectedRow()));
        deleteConfiguration.setVisible(true);
    }//GEN-LAST:event_deleteConfButtonActionPerformed

    private void findConfigsByNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findConfigsByNameButtonActionPerformed
        if (searchNameLabel.getText().isEmpty() || searchNameLabel.getText() == null) {
            WarningDialog warningDialog = new WarningDialog(this, true);
            warningDialog.setSize(365, 140);
            warningDialog.setWarningLabel(bundle.getString("searchByNameEmpty"));
            warningDialog.setVisible(true);
        } else {
            findAllConfigurationsByName(searchNameLabel.getText());
        }
    }//GEN-LAST:event_findConfigsByNameButtonActionPerformed

    private void showAllConfsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllConfsButtonActionPerformed
        SwingWorker<Set<Configuration>, Void> worker = new SwingWorker<Set<Configuration>, Void>() {

            @Override
            protected Set<Configuration> doInBackground() throws Exception {
                return configManager.findAllConfigurations();
            }

            @Override
            protected void done() {
                try {
                    if (get().isEmpty()) {
                        WarningDialog warningDialog = new WarningDialog(mainWindow, true);
                        warningDialog.setSize(365, 140);
                        warningDialog.setWarningLabel(bundle.getString("noConfigurationInDB"));
                        warningDialog.setVisible(true);
                    } else {
                        configModel.loadConfigurations(get());
                        configModel.fireTableDataChanged();
                    }
                } catch (InterruptedException | ExecutionException ex) {
                    LOGGER.log(Level.SEVERE, "Error getting configurations from database to table: ", ex);
                }
            }
        };

        worker.execute();
        editConfButton.setEnabled(false);
        deleteConfButton.setEnabled(false);
    }//GEN-LAST:event_showAllConfsButtonActionPerformed

    private void configsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configsTableMouseClicked
        currentConfiguration = configModel.getConfigurationAt(configsTable.convertRowIndexToModel(configsTable.getSelectedRow()));
        confNameTextBox.setText(currentConfiguration.getName());
        createdOnTextBox.setText(currentConfiguration.getCreationTime().format(DateTimeFormatter.ISO_LOCAL_TIME) + " - " + currentConfiguration.getCreationTime().format(DateTimeFormatter.ISO_LOCAL_DATE));
        confCreatorTextBox.setText(currentConfiguration.getCreator());
        lastChangedOnTextBox.setText(currentConfiguration.getLastUpdate().format(DateTimeFormatter.ISO_LOCAL_TIME) + " - " + currentConfiguration.getLastUpdate().format(DateTimeFormatter.ISO_LOCAL_DATE));
        addCompToConfButton.setEnabled(true);
        editConfButton.setEnabled(true);
        deleteConfButton.setEnabled(true);
        deleteCompInConfButton.setEnabled(false);
        editAmountButton.setEnabled(false);

        findAllComponentsInConfiguration();
        refreshPriceAndPower();
    }//GEN-LAST:event_configsTableMouseClicked

    private void deleteCompInConfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCompInConfButtonActionPerformed
        editConfButton.setEnabled(false);
        deleteConfButton.setEnabled(false);
        if (currentComponent != null) {
            DeletePcSetDialog dialog = new DeletePcSetDialog(this, true);
            dialog.setCompAndConf(currentConfiguration, currentComponent);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_deleteCompInConfButtonActionPerformed

    private void compsInCofigTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compsInCofigTableMouseClicked
        deleteCompInConfButton.setEnabled(true);
        editAmountButton.setEnabled(true);
        currentComponent = compModel.getComponentAt(compsInCofigTable.convertRowIndexToModel(compsInCofigTable.getSelectedRow()));
    }//GEN-LAST:event_compsInCofigTableMouseClicked

    private void findConfigsByCompButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findConfigsByCompButtonActionPerformed
        findConfigurationsByComponent();
    }//GEN-LAST:event_findConfigsByCompButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCompToConfButton;
    private javax.swing.JComboBox componentsComboBox;
    private javax.swing.JTable compsInCofigTable;
    private javax.swing.JLabel confCreatorTextBox;
    private javax.swing.JLabel confNameTextBox;
    private javax.swing.JTable configsTable;
    private javax.swing.JButton createConfButton;
    private javax.swing.JLabel createdOnTextBox;
    private javax.swing.JButton deleteCompInConfButton;
    private javax.swing.JButton deleteConfButton;
    private javax.swing.JButton editAmountButton;
    private javax.swing.JButton editConfButton;
    private javax.swing.JButton findConfigsByCompButton;
    private javax.swing.JButton findConfigsByNameButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lastChangedOnTextBox;
    private javax.swing.JTextField searchNameLabel;
    private javax.swing.JButton showAllConfsButton;
    private javax.swing.JLabel totalPowerLabel;
    private javax.swing.JLabel totalPriceLabel;
    // End of variables declaration//GEN-END:variables

    public void createConfiguration(CreateConfigurationDialog dialog, String name, String creator) {
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {

            @Override
            protected Void doInBackground() throws Exception {
                Configuration conf = new Configuration(name, creator);
                try {
                    configManager.createConfiguration(conf);
                    dialog.dispose();
                } catch (IllegalArgumentException ex) {
                    WarningDialog warningDialog = new WarningDialog(mainWindow, true);
                    warningDialog.setSize(365, 140);
                    warningDialog.setWarningLabel(bundle.getString("configAlreadyExists"));
                    warningDialog.setVisible(true);
                }
                return null;
            }

            @Override
            protected void done() {
                configModel.loadConfigurations(configManager.findAllConfigurations());
                configModel.fireTableDataChanged();
            }
        };

        worker.execute();
    }

    public void updateConfiguration(EditConfigurationDialog dialog, String name, String creator) {
        String oldName = name;
        String oldCreator = creator;
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {

            @Override
            protected Void doInBackground() throws Exception {
                configuration.setName(name);
                configuration.setCreator(creator);
                try {
                    configManager.updateConfiguration(configuration);
                    dialog.dispose();
                } catch (IllegalArgumentException ex) {
                    WarningDialog warningDialog = new WarningDialog(mainWindow, true);
                    warningDialog.setSize(365, 140);
                    warningDialog.setWarningLabel(bundle.getString("configAlreadyExists"));
                    warningDialog.setVisible(true);
                    configuration.setName(oldName);
                    configuration.setCreator(oldCreator);
                }
                return null;
            }

            @Override
            protected void done() {
                configModel.loadConfigurations(configManager.findAllConfigurations());
                configModel.fireTableDataChanged();
            }
        };

        worker.execute();
    }

    public void deleteConfiguration(Configuration configuration) {
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {

            @Override
            protected Void doInBackground() throws Exception {
                Set<Component> comps = pcSetManager.listCompsInConfiguration(configuration).keySet();
                comps.stream().forEach((comp) -> {
                    pcSetManager.deletePcSet(pcSetManager.getPcSet(configuration, comp));
                });

                configManager.deleteConfiguration(configuration);
                return null;
            }

            @Override
            protected void done() {
                configModel.loadConfigurations(configManager.findAllConfigurations());
                configModel.fireTableDataChanged();
                compModel.loadComponents(new TreeMap<Component, Integer>());
                compModel.fireTableDataChanged();
                refreshPriceAndPower();
                confNameTextBox.setText("");
                confCreatorTextBox.setText("");
                createdOnTextBox.setText("");
                lastChangedOnTextBox.setText("");
            }
        };

        worker.execute();
    }

    private void findAllConfigurationsByName(String name) {
        SwingWorker<Set<Configuration>, Void> worker = new SwingWorker<Set<Configuration>, Void>() {

            @Override
            protected Set<Configuration> doInBackground() throws Exception {
                return configManager.findConfigurationByName(name);
            }

            @Override
            protected void done() {
                try {
                    if (get().isEmpty()) {
                        WarningDialog warningDialog = new WarningDialog(mainWindow, true);
                        warningDialog.setSize(365, 140);
                        warningDialog.setWarningLabel(bundle.getString("noConfigurationFound"));
                        warningDialog.setVisible(true);
                    } else {
                        configModel.loadConfigurations(get());
                        configModel.fireTableDataChanged();
                    }
                } catch (InterruptedException | ExecutionException ex) {
                    LOGGER.log(Level.SEVERE, "Error getting configurations from database to table: ", ex);
                }
            }
        };

        worker.execute();
    }

    private void findAllConfigurations() {
        SwingWorker<Set<Configuration>, Void> worker = new SwingWorker<Set<Configuration>, Void>() {

            @Override
            protected Set<Configuration> doInBackground() throws Exception {
                return configManager.findAllConfigurations();
            }

            @Override
            protected void done() {
                try {
                    configModel.loadConfigurations(get());
                    configModel.fireTableDataChanged();
                } catch (InterruptedException | ExecutionException ex) {
                    LOGGER.log(Level.SEVERE, "Error getting configurations from database to table: ", ex);
                }
            }
        };
        worker.execute();
    }

    private void findConfigurationsByComponent() {
        SwingWorker<Set<Configuration>, Void> worker = new SwingWorker<Set<Configuration>, Void>() {

            @Override
            protected Set<Configuration> doInBackground() throws Exception {
                Component comp = (Component) compManager.findAllComponents().toArray()[componentsComboBox.getSelectedIndex()];
                return pcSetManager.findConfigByComponent(comp);
            }

            @Override
            protected void done() {
                try {
                    if (get().isEmpty()) {
                        WarningDialog warningDialog = new WarningDialog(mainWindow, true);
                        warningDialog.setSize(365, 140);
                        warningDialog.setWarningLabel(bundle.getString("noConfigurationFound"));
                        warningDialog.setVisible(true);
                    } else {
                        configModel.loadConfigurations(get());
                        configModel.fireTableDataChanged();
                        deleteConfButton.setEnabled(false);
                        editConfButton.setEnabled(false);
                    }
                } catch (InterruptedException | ExecutionException ex) {
                    LOGGER.log(Level.SEVERE, "Error getting configurations from database to table: ", ex);
                }
            }
        };

        worker.execute();
    }

    private void findAllComponentsInConfiguration() {
        SwingWorker<Map<Component, Integer>, Void> worker = new SwingWorker<Map<Component, Integer>, Void>() {

            @Override
            protected Map<Component, Integer> doInBackground() throws Exception {
                return pcSetManager.listCompsInConfiguration(currentConfiguration);
            }

            @Override
            protected void done() {
                try {
                    compModel.loadComponents(get());
                    compModel.fireTableDataChanged();
                } catch (InterruptedException | ExecutionException ex) {
                    LOGGER.log(Level.SEVERE, "Error getting components from database to table: ", ex);
                }
            }
        };

        worker.execute();
    }

    public void deletePcSet(Component component, Configuration configuration) {
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {

            @Override
            protected Void doInBackground() throws Exception {
                pcSetManager.deletePcSet(pcSetManager.getPcSet(configuration, component));
                return null;
            }

            @Override
            protected void done() {
                compModel.loadComponents(pcSetManager.listCompsInConfiguration(configuration));
                compModel.fireTableDataChanged();
                configModel.loadConfigurations(configManager.findAllConfigurations());
                configModel.fireTableDataChanged();
                changeLastUpdateLabel(currentConfiguration);
                refreshPriceAndPower();
                editAmountButton.setEnabled(false);
                deleteCompInConfButton.setEnabled(false);
            }
        };

        worker.execute();
    }

    public void createPcSet(AddCompToConfDialog dialog, Component component, Integer count) {
        SwingWorker<Map<Component, Integer>, Void> worker = new SwingWorker<Map<Component, Integer>, Void>() {

            @Override
            protected Map<Component, Integer> doInBackground() throws Exception {
                PcSet newSet = new PcSet(component, currentConfiguration, (int) count);
                try {
                    pcSetManager.createPcSet(newSet);
                    dialog.dispose();
                } catch (IllegalArgumentException ex) {
                    WarningDialog warningDialog = new WarningDialog(mainWindow, true);
                    warningDialog.setSize(460, 140);
                    warningDialog.setWarningLabel(bundle.getString("invalidNumberOfComponents"));
                    warningDialog.setVisible(true);
                } catch (InternalFailureException ex) {
                    WarningDialog warningDialog = new WarningDialog(mainWindow, true);
                    warningDialog.setSize(400, 140);
                    warningDialog.setWarningLabel(bundle.getString("pcSetAlreadyExists"));
                    warningDialog.setVisible(true);
                }
                return pcSetManager.listCompsInConfiguration(currentConfiguration);
            }

            @Override
            protected void done() {
                try {
                    changeLastUpdateLabel(currentConfiguration);
                    compModel.loadComponents(get());
                    compModel.fireTableDataChanged();
                    configModel.loadConfigurations(configManager.findAllConfigurations());
                    configModel.fireTableDataChanged();
                    refreshPriceAndPower();
                    editAmountButton.setEnabled(false);
                    deleteCompInConfButton.setEnabled(false);
                } catch (InterruptedException | ExecutionException ex) {
                    LOGGER.log(Level.SEVERE, "Error getting components in configuration from database to table: ", ex);
                }
            }
        };

        worker.execute();
    }

    public void updatePcSet(EditAmountDialog dialog, Configuration configuration, Component component, int amount) {
        SwingWorker<Map<Component, Integer>, Void> worker = new SwingWorker<Map<Component, Integer>, Void>() {

            @Override
            protected Map<Component, Integer> doInBackground() throws Exception {
                try {
                    pcSetManager.updatePcSet(new PcSet(component, configuration, amount));
                    dialog.dispose();
                } catch (IllegalArgumentException ex) {
                    WarningDialog warningDialog = new WarningDialog(mainWindow, true);
                    warningDialog.setSize(460, 140);
                    warningDialog.setWarningLabel(bundle.getString("invalidNumberOfComponents"));
                    warningDialog.setVisible(true);
                }

                return pcSetManager.listCompsInConfiguration(configuration);
            }

            @Override
            protected void done() {
                try {
                    editAmountButton.setEnabled(false);
                    deleteCompInConfButton.setEnabled(false);
                    changeLastUpdateLabel(currentConfiguration);
                    compModel.loadComponents(get());
                    compModel.fireTableDataChanged();
                    configModel.loadConfigurations(configManager.findAllConfigurations());
                    configModel.fireTableDataChanged();
                    refreshPriceAndPower();
                } catch (InterruptedException | ExecutionException ex) {
                    LOGGER.log(Level.SEVERE, "Error updating number of components in PCSet: ", ex);
                }
            }
        };

        worker.execute();
    }

    public void refreshPriceAndPower() {
        double price = 0;
        Integer power = 0;
        Iterator it = pcSetManager.listCompsInConfiguration(currentConfiguration).entrySet().iterator();

        while (it.hasNext()) {
            Map.Entry pairs = (Map.Entry) it.next();
            Component tempComponent = (Component) pairs.getKey();

            Integer count = ((Integer) pairs.getValue()) == 0 ? 1 : ((Integer) pairs.getValue());
            price += tempComponent.getPrice().doubleValue() * count;
            power += tempComponent.getPower() * count;
            it.remove(); // avoids a ConcurrentModificationException
        }

        totalPriceLabel.setText((new BigDecimal(price)).setScale(2, BigDecimal.ROUND_HALF_UP).toString());
        totalPowerLabel.setText(power.toString());
    }

    private String[] getComponentStrings() {
        List<String> strings = new ArrayList<>();

        compManager.findAllComponents().stream().forEach((comp) -> {
            strings.add(comp.toString());
        });

        String[] strings2 = new String[strings.size()];
        strings.toArray(strings2);
        return strings2;
    }

    public void refreshComponentsComboBox() {
        componentsComboBox.setModel(new DefaultComboBoxModel(getComponentStrings()));
    }

    public void refreshCompAndConfModel() {
        editAmountButton.setEnabled(false);
        deleteCompInConfButton.setEnabled(false);
        SwingWorker<Map<Component, Integer>, Void> worker = new SwingWorker<Map<Component, Integer>, Void>() {

            @Override
            protected Map<Component, Integer> doInBackground() throws Exception {
                return pcSetManager.listCompsInConfiguration(currentConfiguration);
            }

            @Override
            protected void done() {
                try {
                    compModel.loadComponents(get());
                    compModel.fireTableDataChanged();
                    configModel.loadConfigurations(configManager.findAllConfigurations());
                    configModel.fireTableDataChanged();
                } catch (InterruptedException | ExecutionException ex) {
                    LOGGER.log(Level.SEVERE, "Error refreshing component and configuration Table models: ", ex);
                }
            }
        };

        if (currentConfiguration != null) {
            worker.execute();
        }
    }

    public void changeLastUpdateLabel(Configuration conf) {
        lastChangedOnTextBox.setText(conf.getLastUpdate().format(DateTimeFormatter.ISO_LOCAL_TIME) + " - " + conf.getLastUpdate().format(DateTimeFormatter.ISO_LOCAL_DATE));
    }
}
